on: [push, pull_request]
name: Test action
jobs:
  latest:
    runs-on: ubuntu-latest
    name: Download latest PaperMC
    steps:
      - name: Download using own action
        uses: just-dev-creator/install-paper@master
        with:
          path: './paper.jar'
      - name: Check if file exists
        run: file paper.jar
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Start program
        run: "java -jar paper.jar"
        timeout-minutes: 2
  specific_version:
    runs-on: ubuntu-latest
    name: Download latest PaperMC 1.16.5 build
    steps:
      - name: Download using own action
        uses: just-dev-creator/install-paper@master
        with:
          path: './paper.jar'
          version: '1.16.5'
      - name: Check if file exists
        run: file paper.jar
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Start program
        run: "java -jar paper.jar"
        timeout-minutes: 2
  specific_version_build:
    runs-on: ubuntu-latest
    name: Download specific PaperMC
    steps:
      - name: Download using own action
        uses: just-dev-creator/install-paper@master
        with:
          path: './paper.jar'
          version: '1.14.4'
          build_numbeR: '187'
      - name: Check if file exists
        run: file paper.jar
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Start program
        run: "java -jar paper.jar"
        timeout-minutes: 2
